export { HelpMenu as helpMenu } from './Help';
export { SpecialHelp as specialHelp } from './Help';
export { default as clearFunction } from './Clear';
export { default as kickUser } from './Kick';
export { default as banUser } from './Ban';
export { default as sendMessage } from './Send';
export { default as spamUser } from './Spam';
export { default as getInstagramUser } from './Instagram';
export { default as coinFlip } from './Coinflip';
